### ISSUE TITLE
Configuration - Allow specifying directories

### ISSUE THREAD

**Issue by colin-jack** [mozilla/connect-cachify#12]
Currently you allow associating a production URL to the development URLs, however in some cases all the development files will be in the same folder. 

Would it thus be possible to associate a production URL with a folder, and all the JS files in that folder would be used.

**Comment by ozten** [comment]
Sorry I missed this question. Can you provide a hypothetical usage?

**Comment by ozten** [comment]
Closing down. Please re-open with more details.
