### ISSUE TITLE
cachify injects stuff into the global namespace 

### ISSUE THREAD

**Issue by lloyd** [mozilla/connect-cachify#16]
```
$ node
> require('connect-cachify');
{ setup: [Function],
  cachify_js: [Function],
  cachify_css: [Function],
  cachify: [Function] }
> cachify_js
[Function]
```

In BrowserID, we actually _rely_ on this behavior (maybe accidentally?).  In our templates we use cachify functions and we never actually pass them in.

I'd think it might be safer to not inject into the global namespace.  I'd write a patch if you agreed, but what do you think?

**Comment by seanmonstar** [comment]
Keep the global clean! And, I imagine express lets us define default function helpers to templates.

**Comment by lloyd** [comment]
yes!  @zcarter taught me this one:

```
res.local('cachify_js', cachify.cachify_js);
```

is all we would have to add to keep things going in browserid.

**Comment by ozten** [comment]
My bad. Please fix.
