### ISSUE TITLE
util.format not available on node v0.4.11 on Heroku.

### ISSUE THREAD

**Issue by stomlinson** [mozilla/connect-cachify#3]
@ozten - nice work here!

Unfortunately, Heroku uses node v0.4.11, which does not have util.format.

**Comment by ozten** [comment]
Ah, great find.

Do libraries with wide compatibility typically do string concatenation with `+`?

**Comment by shane-tomlinson** [comment]
@ozten, unfortunately I'm not sure what the accepted "Node" way of doing things is, doing string concatenation with + has been common on the front end for years though.

**Comment by ozten** [comment]
Coolio, I think this is fixed with https://github.com/mozilla/connect-cachify/commit/6b946af829583c3e6acbd6e444842e38c4a25af8

Published 0.0.3.
