### ISSUE TITLE
truncate hash to 8 characters

### ISSUE THREAD

**Issue by ozten** [mozilla/connect-cachify#5]
Suggested by @mmayo and @lloyd 

We should shorten the hash in urls to 8 characters.

Hashes are always scoped to a filename, so we probably don't need an entire hash for uniqueness.

This has some other nice properties - middleware can handle SHA or MD5 hashes, since they are indistinguishable truncated to 8 characters.

**Comment by vmunix** [comment]
Also food for thought: 10 chars would allow for use of a unix timestamp unaltered.  (i.e. the rails default)

**Comment by ozten** [comment]
Updated docs. Hardcoding to 10 digits. Probably want this to be configurable at some point...

In v0.0.6. v0.0.7 tag coming for another tweak.
